version: '3.8'

services:
  # Dịch vụ 1: Redis Cache
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - music_app_network

  # Dịch vụ 2: Backend chính bằng Node.js
  backend:
    build: .
    container_name: music-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - recommendation-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RECOMMENDATION_API_URL=http://recommendation-service:5001
      # --- BẬT "CÔNG TẮC" THÔNG MINH CHO MÔI TRƯỜDNG LOCAL ---
      - ENABLE_SMART_RECOMMENDATIONS=true 
    networks:
      - music_app_network

  # Dịch vụ 3: API Gợi ý Python (Đã tích hợp tự huấn luyện)
  recommendation-service:
    build:
      context: ./music-recommendation-service
      dockerfile: Dockerfile
    container_name: music-recommendation
    ports:
      - "5001:5001"
    # --- LỆNH KHỞI ĐỘNG THÔNG MINH ---
    # Chạy `train.py` trước, sau đó mới khởi động server Flask trên port 5001
    command: sh -c "python train.py && flask run --host=0.0.0.0 --port=5001"
    networks:
      - music_app_network
    env_file:
      - ./music-recommendation-service/.env

# Định nghĩa network chung để các service có thể "nói chuyện" với nhau
networks:
  music_app_network:
    driver: bridge

