
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: music-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
