# render.yaml
# Phiên bản hoàn chỉnh, chỉ định rõ gói miễn phí cho tất cả các dịch vụ.

services:
  # Dịch vụ 1: Redis Cache
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] 

  # Dịch vụ 2: Backend NodeJS
  - type: web
    name: music-backend-nodejs
    env: docker
    plan: free # <-- THÊM DÒNG NÀY
    rootDir: . 
    dockerfilePath: ./Dockerfile 
    envVars:
      - key: PORT
        value: 5000
      - key: REDIS_HOST
        fromService: { type: redis, name: redis-cache, property: host }
      - key: REDIS_PORT
        fromService: { type: redis, name: redis-cache, property: port }
      - key: RECOMMENDATION_API_URL
        value: "https://music-recommendation-python.onrender.com"
      # Các biến môi trường bí mật
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
        
  # Dịch vụ 3: Service Gợi ý Python
  - type: web
    name: music-recommendation-python
    env: docker
    plan: free # <-- THÊM DÒNG NÀY
    rootDir: ./music-recommendation-service
    dockerfilePath: ./music-recommendation-service/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: RENDER_DISCOVERY 
        value: "true"

  # Dịch vụ 4: Cron Job
  - type: cron
    name: daily-retrainer
    plan: free # <-- THÊM DÒNG NÀY
    schedule: "0 19 * * *" 
    startCommand: "curl -X POST $DEPLOY_HOOK_URL"
    envVars:
      - key: DEPLOY_HOOK_URL
        sync: false

