# render.yaml
# Phiên bản đã được sửa lỗi cú pháp để deploy lên Render.

services:
  # Dịch vụ 1: Redis Cache
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] # SỬA LỖI 1: Thêm danh sách IP cho phép

  # Dịch vụ 2: Backend NodeJS
  - type: web
    name: music-backend-nodejs
    env: docker
    rootDir: . 
    dockerfilePath: ./Dockerfile 
    envVars:
      - key: PORT
        value: 5000
      - key: REDIS_HOST
        fromService: { type: redis, name: redis-cache, property: host }
      - key: REDIS_PORT
        fromService: { type: redis, name: redis-cache, property: port }
      # SỬA LỖI 2: Tự xây dựng URL thay vì dùng fromService
      - key: RECOMMENDATION_API_URL
        value: "https://music-recommendation-python.onrender.com"
      # Các biến môi trường bí mật
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
        
  # Dịch vụ 3: Service Gợi ý Python
  - type: web
    name: music-recommendation-python
    env: docker
    rootDir: ./music-recommendation-service
    dockerfilePath: ./music-recommendation-service/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: RENDER_DISCOVERY
        value: "true"

  # Dịch vụ 4: Cron Job (SỬA LỖI 3: Bỏ runtime)
  - type: cron
    name: daily-retrainer
    schedule: "0 19 * * *" 
    startCommand: "curl -X POST $DEPLOY_HOOK_URL"
    envVars:
      - key: DEPLOY_HOOK_URL
        sync: false
```

#### **Bước 3: Đảm bảo code NodeJS đã được cập nhật**
Hãy chắc chắn rằng file service NodeJS của bạn (ví dụ `collaborative.service.ts`) đang đọc URL từ biến môi trường, như chúng ta đã thảo luận.
```typescript
const RECOMMENDATION_API_URL = process.env.RECOMMENDATION_API_URL || 'http://localhost:5001';

